# Purpose: Configuration for commitlint to enforce conventional commit messages.
extends:
  - "@commitlint/config-conventional"

rules:
  type-enum:
    - 2
    - always
    - [
        "feat",
        "fix",
        "docs",
        "style",
        "refactor",
        "perf",
        "test",
        "build",
        "ci",
        "chore",
        "revert",
        "wip" 
      ]
