#!/usr/bin/env bash
set -euo pipefail

# Script: Inject Secret into .env.secrets.json
# Purpose: Add or update a secret in the encrypted secrets file
#
# Usage:
#   ./scripts/setup/inject-secret.sh KEY VALUE
#   mise run inject-secret KEY VALUE
#
# Examples:
#   mise run inject-secret TELEGRAM_BOT_TOKEN "123456:ABC..."
#   mise run inject-secret DATABASE_PASSWORD "super-secret"
#

SECRETS_FILE=".env.secrets.json"
SECRETS_EXAMPLE="config/.env.secrets.json.example"
AGE_KEY_FILE=".secrets/mise-age.txt"

# Check if key and value are provided
if [ $# -lt 2 ]; then
    echo "Usage: $0 KEY VALUE"
    echo ""
    echo "Examples:"
    echo "  $0 TELEGRAM_BOT_TOKEN '123456:ABC...'"
    echo "  $0 DATABASE_PASSWORD 'super-secret'"
    echo "  mise run inject-secret API_KEY 'sk-...'"
    exit 1
fi

KEY="$1"
VALUE="$2"

echo "========================================="
echo "Injecting Secret into $SECRETS_FILE"
echo "========================================="
echo "Key: $KEY"
echo "Value: ${VALUE:0:10}..." # Show only first 10 chars
echo ""

# Check if age key exists
if [ ! -f "$AGE_KEY_FILE" ]; then
    echo "⚠️  Age key not found at $AGE_KEY_FILE"
    echo "   Generating new age key..."
    ./scripts/setup/generate-age-key.sh

    # Verify key was created
    if [ ! -f "$AGE_KEY_FILE" ]; then
        echo "❌ Failed to create age key at $AGE_KEY_FILE"
        echo ""
        echo "Please run manually:"
        echo "   mise run generate-age-key"
        exit 1
    fi

    echo "✓ Age key created successfully"
    echo ""
fi

# Ensure .sops.yaml exists with the correct age public key
# SOPS uses this file to know how to encrypt files
PUBLIC_KEY=$(grep "public key:" "$AGE_KEY_FILE" | awk '{print $NF}')

if [ -z "$PUBLIC_KEY" ]; then
    echo "❌ Failed to extract public key from $AGE_KEY_FILE"
    exit 1
fi

echo "🔑 Configuring SOPS with age public key..."

# Create or update .sops.yaml
cat > .sops.yaml <<EOF
# SOPS configuration for age encryption
# Auto-generated by inject-secret script

creation_rules:
  # Encrypt .env.secrets.json with age
  - path_regex: \.env\.secrets\.json$
    age: '$PUBLIC_KEY'
EOF

echo "✓ Updated .sops.yaml"
echo ""

# Check if secrets file exists
if [ ! -f "$SECRETS_FILE" ]; then
    echo "📝 Secrets file not found, creating new empty file..."
    echo "   Starting with empty JSON object: {}"

    # Always start with empty JSON object
    echo '{}' > "$SECRETS_FILE"

    # Encrypt the new file (SOPS uses .sops.yaml for encryption rules)
    echo "   Encrypting with age..."
    sops --encrypt --input-type json --output-type json "$SECRETS_FILE" > "${SECRETS_FILE}.tmp"
    mv "${SECRETS_FILE}.tmp" "$SECRETS_FILE"
    echo "✓ Created and encrypted $SECRETS_FILE"
    echo ""
fi

# Inject or update the secret using 'sops set'
# This is much simpler than decrypt → edit → encrypt!
echo "📝 Injecting secret: $KEY"
if ! sops --set "[\"$KEY\"] \"$VALUE\"" "$SECRETS_FILE"; then
    echo "❌ Failed to inject secret"
    echo "   Make sure the file is properly encrypted and you have the correct age key"
    exit 1
fi

echo ""
echo "✅ Secret injected successfully!"
echo ""
echo "Current secrets in file:"
sops --decrypt "$SECRETS_FILE" | jq -r 'keys[]' | sed 's/^/  - /'

echo ""
echo "========================================="
echo "To view all secrets:"
echo "  mise run decrypt-secrets"
echo ""
echo "To edit secrets interactively:"
echo "  mise run edit-secrets"
echo "========================================="
