#!/bin/bash
# CI Stability Tag Management Script - Version 1.0.0
#
# PURPOSE: Manage stability tags (stable/unstable) for version releases
#
# USAGE:
#   ./scripts/ci/deployment/17-ci-manage-stability-tags.sh <stability_type> <version>
#
# EXAMPLES:
#   # Tag version as stable
#   ./scripts/ci/deployment/17-ci-manage-stability-tags.sh "stable" "v1.2.3"
#
#   # Tag version as unstable
#   ./scripts/ci/deployment/17-ci-manage-stability-tags.sh "unstable" "v1.2.3"
#
#   # With test mode
#   CI_TEST_MODE="dry_run" ./scripts/ci/deployment/17-ci-manage-stability-tags.sh "stable" "v1.2.3"
#
# TESTABILITY ENVIRONMENT VARIABLES:
#   - CI_TEST_MODE: Set to "dry_run" to simulate tagging operations
#   - STABILITY_TYPE: Override stability type for testing
#   - VERSION: Override version for testing
#
# EXTENSION POINTS:
#   - Add custom tagging logic in manage_custom_tags()
#   - Extend validation in validate_stability_operation()
#   - Customize tag format in format_stability_tag()
#
# SIZE GUIDELINES:
#   - Keep script under 50 lines (excluding comments and documentation)
#   - Extract complex git operations to helper functions
#   - Use shared utilities for common operations
#
# DEPENDENCIES:
#   - Required: bash, git
#   - Optional: jq (for JSON formatting)

set -euo pipefail

# Script configuration
SCRIPT_NAME="$(basename "$0" .sh)"
SCRIPT_VERSION="1.0.0"
SCRIPT_MODE="${SCRIPT_MODE:-${CI_TEST_MODE:-default}}"

# Source libraries and utilities
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../../lib/config.sh"
source "${SCRIPT_DIR}/../../lib/logging.sh"

# Tagging parameters
STABILITY_TYPE="${1:-}"
VERSION="${2:-}"

# Main stability tag management function
manage_stability_tags() {
    # Validate inputs
    if [[ -z "$STABILITY_TYPE" ]]; then
        log_error "❌ Stability type is required (stable/unstable)"
        exit 1
    fi

    if [[ -z "$VERSION" ]]; then
        log_error "❌ Version is required"
        exit 1
    fi

    log_info "Managing stability tags: $STABILITY_TYPE for version $VERSION"

    # Validate stability operation
    validate_stability_operation

    # Execute tagging operation
    execute_stability_tagging

    # Generate tagging report
    generate_tagging_report

    log_success "✅ Stability tag management completed: $STABILITY_TYPE"
}

# Validate stability operation
validate_stability_operation() {
    local valid_types=("stable" "unstable")
    local is_valid=false

    for type in "${valid_types[@]}"; do
        if [[ "$STABILITY_TYPE" == "$type" ]]; then
            is_valid=true
            break
        fi
    done

    if [[ "$is_valid" != "true" ]]; then
        log_error "❌ Invalid stability type: $STABILITY_TYPE"
        log_error "Valid types: ${valid_types[*]}"
        exit 1
    fi

    log_info "✅ Stability type validated: $STABILITY_TYPE"
}

# Execute stability tagging
execute_stability_tagging() {
    if [[ "$SCRIPT_MODE" == "dry_run" ]]; then
        echo "[DRY RUN] Would tag version $VERSION as $STABILITY_TYPE"
        return 0
    fi

    # Configure git
    git config user.name "github-actions[bot]"
    git config user.email "github-actions[bot]@users.noreply.github.com"

    # Execute tagging
    case "$STABILITY_TYPE" in
        "stable")
            git tag -f stable "$VERSION"
            git push -f origin stable
            ;;
        "unstable")
            git tag -f unstable "$VERSION"
            git push -f origin unstable
            ;;
    esac

    log_info "✅ Tagging completed: $STABILITY_TYPE"
}

# Generate tagging report
generate_tagging_report() {
    local stability_name
    stability_name=$(format_stability_name "$STABILITY_TYPE")

    cat > tagging-summary.md << EOF
# 🏷️ Stability Tagging

## 📋 Tagging Information

**Version:** $VERSION
**Stability:** $(get_stability_icon "$STABILITY_TYPE") $stability_name
**Timestamp:** $(date -u +"%Y-%m-%dT%H:%M:%SZ")

## ✅ Tagging Summary

**Version $VERSION tagged as $stability_name**

The stability tag has been updated successfully. This tag will be used by downstream systems to determine the stability status of this version.

---

*This report was generated by the CI Excellence Framework v$SCRIPT_VERSION*
EOF

    # Output to GitHub Actions
    if [[ "$SCRIPT_MODE" != "dry_run" ]]; then
        cat tagging-summary.md >> "$GITHUB_STEP_SUMMARY"
    fi
}

# Format stability name for display
format_stability_name() {
    local type="$1"
    case "$type" in
        "stable") echo "Stable" ;;
        "unstable") echo "Unstable" ;;
        *) echo "$type" ;;
    esac
}

# Get stability icon
get_stability_icon() {
    local type="$1"
    case "$type" in
        "stable") echo "🟢" ;;
        "unstable") echo "🟡" ;;
        *) echo "⚪" ;;
    esac
}

# Custom tagging logic extension point
manage_custom_tags() {
    # Override this function to add custom tagging logic
    log_debug "Custom stability tagging (no additional logic defined)"
}

# Main function
main() {
    log_info "$SCRIPT_NAME v$SCRIPT_VERSION - Stability Tag Management"

    # Initialize project configuration
    load_project_config

    # Manage stability tags
    manage_stability_tags

    # Run custom extensions if defined
    if command -v manage_custom_tags >/dev/null 2>&1; then
        manage_custom_tags
    fi

    log_success "✅ Stability tag management completed"
}

# Run main function with all arguments
main "$@"