#!/bin/bash
# CI Release Summary Generator Script - Version 1.0.0
#
# PURPOSE: Generate comprehensive release pipeline summaries with status and configuration
#
# USAGE:
#   ./scripts/ci/reporting/32-ci-generate-release-summary.sh
#
# EXAMPLES:
#   # Generate release summary with all pipeline results
#   ./scripts/ci/reporting/32-ci-generate-release-summary.sh
#
#   # With specific results
#   VERSION="1.2.3" IS_PRERELEASE="false" PUBLISH_NPM_RESULT="success" ./scripts/ci/reporting/32-ci-generate-release-summary.sh
#
# TESTABILITY ENVIRONMENT VARIABLES:
#   - CI_TEST_MODE: Set to "dry_run" to simulate summary generation
#   - ENABLE_ACTION_LINKS: Enable/disable action links (default: true)
#
# EXTENSION POINTS:
#   - Add custom release metrics in generate_release_metrics()
#   - Extend summary sections in generate_additional_sections()
#   - Customize formatting in format_summary()
#
# SIZE GUIDELINES:
#   - Keep script under 50 lines (excluding comments and documentation)
#   - Extract complex table generation logic to helper functions
#   - Use templates for different release types
#
# DEPENDENCIES:
#   - Required: bash
#   - Optional: jq (for JSON formatting)

set -euo pipefail

# Script configuration
SCRIPT_NAME="$(basename "$0" .sh)"
SCRIPT_VERSION="1.0.0"
SCRIPT_MODE="${SCRIPT_MODE:-${CI_TEST_MODE:-default}}"

# Source libraries and utilities
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../../lib/config.sh"
source "${SCRIPT_DIR}/../../lib/logging.sh"

# Release information
VERSION="${VERSION:-unknown}"
IS_PRERELEASE="${IS_PRERELEASE:-unknown}"

# Pipeline results (from GitHub Actions)
PUBLISH_NPM_RESULT="${PUBLISH_NPM_RESULT:-unknown}"
PUBLISH_GITHUB_RESULT="${PUBLISH_GITHUB_RESULT:-unknown}"
PUBLISH_DOCKER_RESULT="${PUBLISH_DOCKER_RESULT:-unknown}"
PUBLISH_DOCUMENTATION_RESULT="${PUBLISH_DOCUMENTATION_RESULT:-unknown}"

# Configuration flags
ENABLE_NPM_PUBLISH="${ENABLE_NPM_PUBLISH:-false}"
ENABLE_GITHUB_RELEASE="${ENABLE_GITHUB_RELEASE:-false}"
ENABLE_DOCKER_PUBLISH="${ENABLE_DOCKER_PUBLISH:-false}"
ENABLE_DOCUMENTATION="${ENABLE_DOCUMENTATION:-false}"

# Main release summary function
generate_release_summary() {
    log_info "Generating release pipeline summary"

    # Create summary content
    create_release_summary_content

    # Output to GitHub Actions
    output_to_github_actions

    # Save as artifact
    save_summary_artifact

    log_success "✅ Release summary generated successfully"
}

# Create release summary content
create_release_summary_content() {
    cat > release-summary.md << EOF
# 🚀 Release Pipeline Summary

## 📋 Release Information

**Version:** $VERSION
**Pre-release:** $IS_PRERELEASE

## 📊 Pipeline Results

| Target | Status | Enabled |
|--------|--------|---------|
| NPM | $(get_status_icon "$PUBLISH_NPM_RESULT") | $ENABLE_NPM_PUBLISH |
| GitHub | $(get_status_icon "$PUBLISH_GITHUB_RESULT") | $ENABLE_GITHUB_RELEASE |
| Docker | $(get_status_icon "$PUBLISH_DOCKER_RESULT") | $ENABLE_DOCKER_PUBLISH |
| Documentation | $(get_status_icon "$PUBLISH_DOCUMENTATION_RESULT") | $ENABLE_DOCUMENTATION |

**Generated:** $(date -u +"%Y-%m-%dT%H:%M:%SZ")

---

*This summary was generated by the CI Excellence Framework v$SCRIPT_VERSION*
EOF
}

# Get status icon for results
get_status_icon() {
    local result="$1"
    case "$result" in
        "success") echo "✅ Success" ;;
        "skipped") echo "⏭️ Skipped" ;;
        "failure") echo "❌ Failed" ;;
        "cancelled") echo "🚫 Cancelled" ;;
        *) echo "❓ Unknown" ;;
    esac
}

# Output to GitHub Actions
output_to_github_actions() {
    if [[ "$SCRIPT_MODE" == "dry_run" ]]; then
        echo "[DRY RUN] Would output release summary to GitHub Actions"
        return 0
    fi

    cat release-summary.md >> "$GITHUB_STEP_SUMMARY"
    log_info "Release summary output to GitHub Actions"
}

# Save summary as artifact
save_summary_artifact() {
    mkdir -p summaries
    cp release-summary.md "summaries/release-summary.md"
    log_info "Release summary saved as artifact"
}

# Custom release metrics extension point
generate_release_metrics() {
    # Override this function to add custom release metrics
    log_debug "Custom release metrics (no additional metrics defined)"
}

# Additional summary sections extension point
generate_additional_sections() {
    # Override this function to add custom summary sections
    log_debug "Additional summary sections (no additional sections defined)"
}

# Main function
main() {
    log_info "$SCRIPT_NAME v$SCRIPT_VERSION - Release Summary Generator"

    # Initialize project configuration
    load_project_config

    # Generate release summary
    generate_release_summary

    # Run custom extensions if defined
    if command -v generate_release_metrics >/dev/null 2>&1; then
        generate_release_metrics
    fi

    if command -v generate_additional_sections >/dev/null 2>&1; then
        generate_additional_sections
    fi

    log_success "✅ Release summary generation completed"
}

# Run main function with all arguments
main "$@"